name: Deploy Create Data Lambda
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/create-data/**/*

defaults:
  run:
    working-directory: apps/create-data

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-central-1

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip build
        run: cd build && zip -r ../main.zip .

      - name: Update Lambda Code
        run: aws lambda update-function-code --function-name=new-create-data --zip-file=fileb://main.zip
